// webpack.config.mjs - ES Module configuration
import path from 'path';
import { fileURLToPath } from 'url';
import recursiveLs from 'fs-readdir-recursive';
import CopyWebpackPlugin from 'copy-webpack-plugin';

const filename = fileURLToPath(import.meta.url),
	dirname = path.dirname(filename),
	entries = {},
	buildEntries = (dir) => {
		try {
			// Recursively list files in the specified directory
			recursiveLs(dir).forEach((f) => {
				// Add each file as an entry point with its full path
				entries[f] = path.join(dir, f);
				console.log(`Adding entry: ${f} => ${path.join(dir, f)}`);
			});
		} catch (err) {
			// Handle errors if any occur during directory scanning
			console.error('Error building entries:', err);
		}
	};

// Call buildEntries function to generate entry points from the 'src/main' directory
console.log('Building entries from src/main and src/lib...');
buildEntries(path.resolve(dirname, 'src', 'main'));
buildEntries(path.resolve(dirname, 'src', 'lib'));

// Export webpack configuration
export default {
	// Set development mode for better debugging
	mode: 'development',
	devtool: 'source-map',
	// Specify entry points generated by the buildEntries function
	entry: entries,
	// Define output configuration
	output: {
		// Specify output directory for bundled files
		path: path.resolve(dirname, 'pack'),
		// Define filename pattern for output files
		filename: '[name]',
		module: true,
		chunkFormat: 'module',
		library: {
			type: 'module'
		},
		environment: {
			module: true
		}
	},
	module: {
		rules: [
			{
				test: /\.(m?js)$/,
				exclude: /node_modules/,
				use: {
					loader: 'babel-loader',
					options: {
						presets: [
							['@babel/preset-env', {
								targets: {
									browsers: ['last 2 versions']
								},
								modules: false
							}]
						]
					}
				}
			}
		]
	},
	resolve: {
		extensions: ['.mjs', '.js'],
		extensionAlias: {
			'.js': ['.mjs', '.js']
		}
	},
	plugins: [
		new CopyWebpackPlugin({
			patterns: [
				{
					from: './template',
					to: '.',
					force: true,
					globOptions: {
						ignore: [
							// Exclude the old .js files that we've migrated
							'**/prompt.js',
							'**/options-gremlins-bookmarklet-handler.js',
							'**/gremlins-handler.js',
							'**/popup-init.js',
							'**/popup.js',
							'**/background.mjs'  // Exclude template background.mjs to use built version
						]
					}
				}
			]
		})
	],
	optimization: {
		minimize: false // Disables all forms of minimization
	},
	experiments: {
		outputModule: true,
		topLevelAwait: true
	}
};
